### ISSUE TITLE
Setup initial Electron shell wrapper - [3]

### ISSUE THREAD

**Issue by techninja** [PancakeBot/PancakeCreator#2]
Includes basics for build system, root js, and renderer. Verify build and runtimes.
Should also include setup of minimum window size and window defaults & basic menus

**Comment by Slimmy82** [comment]
Hi James, I will be in there hangout now. Meet me there when you get a chance. Thanks
Slim Geransar
(646)706-3382
slim@storebound.com<mailto:slim@storebound.com>

[cid:CE92FAD3-CF75-4CDD-A3D3-9B390309CBAB]

On Jul 27, 2015, at 1:14 PM, James T <notifications@github.com<mailto:notifications@github.com>> wrote:


Includes basics for build system, root js, and renderer. Verify build and runtimes. [3]

**Comment by techninja** [comment]
Root is in, basic build is working on Windows & Mac with size constraints. Will complete tomorrow morning.
