### ISSUE TITLE
Gold Standard Example GCode Needed

### ISSUE THREAD

**Issue by techninja** [PancakeBot/PancakeCreator#22]
Given the "bull" GCode example to base my simulation code off, I've done a quick analysis on the movement data:

```
G1 Move:
X: {min: 216.876, max: 623.116}
Y: {min: 27, max: 393}
```

Our draw area should look something like this:

```
 [485, 0]                 [42, 0]
    +-----------------------+    
    |                       |    
    |                       |    
    |                       |    
    |                       |    
    +-----------------------+    
[485, 210]              [42, 210]
```

And I'm assuming the design diagram I got shows the "front" of the bot here to the bottom, meaning the "top right" of the bot is the home position and `[0, 0]`.

This means our "perfect" GCode is upside down, and flies way off the left edge and bottom by nearly 200mm?
### What's needed for this ticket to be done:
- [x] Final accepted GCODE command list
- [x] GCODE specialty commands for pause/bottle change (#25)
- [x] Confirmed x/y Top left, bottom right limits
- [x] Semi optional: Full tested GCODE drawing example

**Comment by techninja** [comment]
Here's the bull Gcode source for reference:

http://pastebin.com/raw.php?i=KNp2UxFD

**Comment by techninja** [comment]
Also interesting is this passage in the middle for the switch from outline to the head of the bull:

```
...
G1 X235.956 Y206.640
G1 X237.516 Y203.710
M107 ; Pump Off
G1 X239.116 Y201.314 ; Outline ^^
M106 ; Pump On
M84 S2 ; Pause (2 seconds)
G1 X369.641 Y95.103 ; Bull Head (from here down)
G1 X370.855 Y90.840
...
```

The pump turns off right before the last movement to complete the outline, that's great, and expected. But right before it moves to the inside image, it turns the pump back on (basically immediately), waits a full 2 seconds then draws a big messy line from the outline to the head. Does that seem right? :P

**Comment by Slimmy82** [comment]
Not sure about this. We will need to wait till we have a machine to test on

**Comment by techninja** [comment]
The creation of a simulator as described in #11 is meant to alleviate this, at least temporarily. Initial work (with heavily adjusted dimensions, see first comment) has resulted in the following output for the untouched bull:
![Original Bull GCode](https://cloud.githubusercontent.com/assets/320747/9179419/52360dde-3f51-11e5-95c2-250c03703b9e.png)

I then adjusted the position of the pump on and wait to be **_after_** the move to the next point (as expected), and got this:
![adjusted bull](https://cloud.githubusercontent.com/assets/320747/9179435/7b3163e6-3f51-11e5-9b8a-7c989be16c18.png)

Either something very weird is going on with how these instructions are meant to work or be executed, or the given bull GCode is wrong. Will test with my other example.

**Comment by techninja** [comment]
Testing with Miguel's Star Wars ATAT GCode file doesn't yield much better in the realm of accuracy to the draw limits, and it uses a different format of G1 (G00?). Regardless, I've built the simulator with universal remap, allowing completely custom limits to be set for rendering, so here it is!

![Pancake Simulated ATAT](https://cloud.githubusercontent.com/assets/320747/9244690/78082210-4152-11e5-8ede-6d4b60db0398.png)

The green line is the "perfect" path to be followed, and the whiteish is obviously the simulated batter. The line on the right appears to be a cleanup line mentioned by Miguel needed for calibration. Unless that's in the gold standard, I'm not going to have something like that automatically added.

This properly approximates batter pump warm up and turn off lag, as can be seen in the occasional trail off. I suspect the problem seen in this gcode isn't nearly as bad on a real bot... but of course I've not yet seen one. The great thing is the warm up timing on this is perfect (as it uses fractions of a second for timing, something I believe is going to be 100% required for the firmware).

I'm going to continue to move between the two GCODE examples here, but I hope to see a new official GCODE from the guys in China after tooling is done that we can base our standard on.

**Comment by Slimmy82** [comment]
More than likely China are clueless about Gcode. Rather, we may want to send them a gcode file and have them test it to see the results.

**Comment by techninja** [comment]
That's certainly possible. Of course, didn't they give us the "bull" GCODE? I'd say it's a fine start to say "tell us how this prints", because according to what I've seen from their GCODE limits, it will come out terribly and it will help them understand we need something different, otherwise it's going to be quite a surprise when we get our first bot.

**Comment by techninja** [comment]
Ok, Miguel emailed me a template of how dimensions are meant to be:

![griddlelayoutfinal](https://cloud.githubusercontent.com/assets/320747/9413365/52fe7984-47e6-11e5-9d04-009b6127fe92.jpg)

This is apparently not in MM, unless the width of the griddle is nearly 4 feet wide :straight_ruler: :stuck_out_tongue_closed_eyes: 

This expands the "printable" area by a notable amount, and doesn't do much to clarify the "top/bottom" issue, so I've asked for clarification and should get more info soon.

**Comment by techninja** [comment]
Looks Like we have final confirmation on general GCODE commands! Will make list of remaining todos for this ticket in top comment.

**Comment by i-make-robots** [comment]
G0 and G1 are the same, but traditionally G1 was meant to indicate a rapid move between two work areas.  The initial drawing area makes my head hurt - normally images have their origin in the top left.  If the pancakeBot were turned 90 deg counter, the coordinate systems would match and the math gets easier.  I suppose it doesn't really matter, I just needed to get it off my chest.

**Comment by techninja** [comment]
I believe we've cleared up the GCODE oddities as Miguel sent them what he actually wanted and they adjusted. I think. See latest 0.9.5 GCODE output here: https://github.com/PancakeBot/PancakeCreator/issues/30#issuecomment-137858259

**Comment by techninja** [comment]
I'm closing this out as I have something close-ish to real GCODE as used by the bot. There's a few header things I probably don't need to do, but my best guess is I'm just going to have to make the standard as one is unlikely to show up. Neat thing is this is all open source, so if it's wrong, it can be "easily" corrected :)
