### ISSUE TITLE
UI Design Sample

### ISSUE THREAD

**Issue by Slimmy82** [PancakeBot/PancakeCreator#26]
Here is a sample UI design. 

-The griddle is larger to fill up the horizontal space
-Icons centered above the griddle.
    -The color pallet for shades needs to be adjusted to match current
    -A red box can be placed around the icon showing that it is selected, similar to shade selection (open         to other suggestions
-Logo underneath

Files can be found here
https://www.dropbox.com/sh/ycwrgf1sopxb3yy/AAAfaAAloeLcdEAZiMgIBTRWa?dl=0
![sampleui](https://cloud.githubusercontent.com/assets/13441968/9317480/e3c86284-4509-11e5-9fca-45c9a34c17a1.png)

**Comment by techninja** [comment]
I hazard to note that maximized/fullscreen for a 16x9 screen (with taskbar, etc), it's our horizontal space that we have more of:
![pancakecreator_004](https://cloud.githubusercontent.com/assets/320747/9344251/109a16ba-45bc-11e5-92a8-41bc9b9c96fa.png)

Note that this is entirely dependent on the resolution and size of the screen. Size of UI elements like the logo and the toolbar (along with the left/right margin) are set absolutely in pixels, so as the size of your screen goes up, these elements are far smaller in relation. 

Here's at around half screen windowed on a 1920x1080 (full HD) display:
![pancakecreator_005](https://cloud.githubusercontent.com/assets/320747/9344341/d19610a8-45bc-11e5-8a5a-1196d30ba077.png)

And here's maximized on a 4k UHD display running at ~100DPI (High res macs run around same resolution, but > 300dpi):
![f0a6eyv](https://cloud.githubusercontent.com/assets/320747/9345293/3a524b82-45c4-11e5-9346-ca7ccf19befd.png)

**Comment by Slimmy82** [comment]
Ah ok, so is it better to have the toolbar on the left instead of the top?

**Comment by techninja** [comment]
Well.. I think it's a bit up in the air. You should likely get a chance to play around with this before you make a decision, I'll see if I can't get you a build out by tomorrow mid-day.

It personally does not feel "bad" to me, but it may feel awkward to others. And the benefit of a side mounted toolbar decreases considerably from an already small amount the larger the screen is. Shrinking/nixing the logo may get us more, but it pulls the canvas away from center horizontally. These are commonly not trivially solved issues, and will definitely take some tweaking to get right.

**Comment by techninja** [comment]
@Slimmy82 Alright, this is basically ready for testing: [PancakeCreator_DesignTest](http://tn42.com/PancakeCreator_DesignTest.zip). Lemme know how that feels for various resized states.

**Comment by Slimmy82** [comment]
Maybe make the logo on the bottom smaller, other than that I am happy with it for now. Thanks.

**Comment by techninja** [comment]
Currently the height of the logo is matched with the toolbar so the griddle remains completely centered. I can cut the height of the logo by half (or maybe 1/3), and then shift the centering down by that much, but I'm not sure it's worth the visual offset. You want me to make you a new build with this so you can see, or should we just keep it where it is?

**Comment by Slimmy82** [comment]
It's ok leave it for now. I rather get other things done. We can make it happen for the next build. No rush with this, we may even need to edit some other elements, depending on how the team likes it tomorrow.

**Comment by techninja** [comment]
Got. Feel free and show off the design with this build then.

**Comment by techninja** [comment]
I'm going to call the work on this done for now. Feel free to open a new issue when you decide on the "final" release design.
