### ISSUE TITLE
Interface concepts

### ISSUE THREAD

**Issue by Slimmy82** [PancakeBot/PancakeCreator#31]
Here is a concept for the interface. Is this feasible? If so, I will present it to the team for confirmation.
![interface_draft](https://cloud.githubusercontent.com/assets/13441968/9564814/ba94bab4-4e7f-11e5-9c0d-4ea6fae11e1e.jpg)

**Comment by techninja** [comment]
Perfectly feasible. Notes:
- That batter implement is looking more and more like a baby bottle :baby_bottle::baby:  
- Is the color on the tip of the bucket/bottle intended to match the shade selected?
- What's the "selected tool" look like? Rounded rectangle border like last time? Same for the rounded color selection?
  - Perhaps for the large icons, also a background color change?
- It's likely we should try to be consistent with fill direction when it comes to cursors, EG, bottle is pointing left, fill icon should probably be left, not right. This is the one I'm currently using:
  - ![cursor-fill](https://cloud.githubusercontent.com/assets/320747/9572059/a43c24bc-4f5d-11e5-9e61-43aa8fa18801.png)
  - I especially like the idea that it's like a measuring cup filled with batter :smile: 
- Would the selection cursor be large and white like the icon? Like colors work well on the darkish-grey background, but I have to put a while & black stroke on all the icons anyways :/
- I'm guessing the "dark grey sun" in the image import icon is a flub and I'll be keeping it how it currently looks.
- Looks like we're keeping the griddle vertically aligned absolutely between the bottom and the top, meaning there will be the same amount of margin at the bottom and at the top? Without the logo at the bottom we can also shift down and take more vertical space at most wider widths.

Everything else is straightforward and understood.

**Comment by Slimmy82** [comment]
Is this version a little better?
<img width="551" alt="screen shot 2015-08-31 at 3 48 22 pm" src="https://cloud.githubusercontent.com/assets/13441968/9588843/87ca36e8-4ff8-11e5-885a-2d1f1d690415.png">
- Not sure how we should make it look like when the tool is selected. Maybe a rounded corner square background darker than the grey in the bar. 
- I think the arrow tool should be the same as the icon like the others yeah?
- The colors of the icons are not really white they are the same grey as the background of the window. light grey.
- The sun is transparent so the grey is the same as the bar grey behind the icon. 
- Not entirely sure what you mean about margins but go with what you recommend.

**Comment by techninja** [comment]
Notes:
- Looking good, definite improvement. Batter depositing fill & line look great, and should work fine.
- I can try both lighter and darker rounded grey backgrounds for tool selection, but it's better to have a final design approved first.
  - This doesn't solve the selection for the shade selection circles.
- Yes, I'll make sure the icons match the cursors for each tool.
- I'll match the "white" to the grey.. though it should be noted it is a very slight radial gradient, I'll just match the outside grey.
- Why the sun is transparent is a bit... odd, but I suppose it helps make it look more like a pancake drawing? I figured anything to help the icon be clear about its intentions as something to import/manage photographs or graphics would be useful for users.
- Still no answer on the pancake shade color match for the fill/line icons/cursors. I'm going to say the UI doesn't really need it, and it's an extra if you really want it.
- I'll keep the margins as they are, matched, and you can play around with it on the next build and see if you like it.

I'm going to continue holding off on implementing any of this till I hear an final OK from you that it's exactly what you (and the design staff etc.) are looking for, then I'll match it exactly and we can get the next build out.

**Comment by Slimmy82** [comment]
Great I appreciate the feedback. I will get approval before you spend any time on it.

**Comment by techninja** [comment]
Discussion is always good and takes up a _tiny percentage_ of time that implementation takes, it's just how things should be done. :)

Hopefully you've got enough to go on here to make the "final" design. It should be noted that I fully expect the design to possibly go through one more iteration after you get the working app in your hands. A Photoshop mockup is one thing, but actually using the app is quite another.

**Comment by techninja** [comment]
Oh hey, almost forgot: Were we still going to have some helper text for users about which direction their pancake is going ala #28 ? Needs to be in the "final" design if so.

**Comment by Slimmy82** [comment]
Hi James, 
Can you please cal me when you are free to briefly discuss UI?

**Comment by Slimmy82** [comment]
<img width="573" alt="screen shot 2015-09-04 at 12 54 18 pm" src="https://cloud.githubusercontent.com/assets/13441968/9694280/2916253c-5325-11e5-8fd7-b888cd719961.png">

**Comment by Slimmy82** [comment]
"The design above will resemble the actual pancake once it has been flipped." does this make sense?

**Comment by techninja** [comment]
Sure does. I'll put it in, and if you have a change of heart, it's easy to fix in the translation strings :)
