### ISSUE TITLE
Mouse Icon/curser reverts to default system

### ISSUE THREAD

**Issue by Slimmy82** [PancakeBot/PancakeCreator#34]
e.g. When you click on the draw tool the icon changes to that icon. when you start drawing it randomly changes to the default system curser. Restarting the application doesn't fix the issue. Restarting resolves it. However it randomly reverts back when you open the app for the 4th or 5th time.

**Comment by techninja** [comment]
Official word on this is that if it works at all, and doesn't "sometimes", then it's likely a bug in the Chromium browser version. For the next build I'll up the version to the latest and we should see both general speed improvements and likely this issue disappear.

**Comment by Slimmy82** [comment]
Great, lets hope so

**Comment by techninja** [comment]
No updates on this for a while, guessing it's fixed.
