### ISSUE TITLE
Vote for Linux Release Support

### ISSUE THREAD

**Issue by techninja** [PancakeBot/PancakeCreator#39]
Only Mac and Windows have official releases, though the app works for Linux as well. Post here to cast your vote for adding Linux to the release list.

**Comment by Al2zone** [comment]
Ubuntu!  13.04+ is fine.

**Comment by raster** [comment]
A Linux release would be awesome!

**Comment by bdale** [comment]
We're a Linux-only household... happy to build from source if we need to, but a Debian-compatible package would be awesome!

**Comment by totto** [comment]
please - we are also a pure linux household :)

**Comment by peteruithoven** [comment]
+1 (Elementary OS)

**Comment by bdale** [comment]
FWIW, I have the current code running on my Debian notebook just fine...

**Comment by raemarks** [comment]
+1 for Fedora! I would love this to be fully supported on Linux.

**Comment by TechRunner2** [comment]
Arch and Ubuntu Packages would be amazing. Even just on the aur.

**Comment by ikanc** [comment]
+1 for linux! :+1:

**Comment by shbert** [comment]
+1 for linux.. rapberry

**Comment by mosburn** [comment]
+1

**Comment by magnets99** [comment]
x64 ubuntu or a raspberry pi build would be great!

**Comment by drtorq** [comment]
Here's an article I wrote on running the PancakePainter on Ubuntu.
["Hack the Pancake Stack: Running PancakeBot under Xubuntu Linux" ](http://thenewstack.io/hack-robot-stack-pancakebot-running-xubuntu-linux/)

**Comment by bmcage** [comment]
+1

**Comment by techninja** [comment]
![goodnews](https://cloud.githubusercontent.com/assets/320747/21464629/974bf390-c937-11e6-8220-e89374067e04.jpg)

Thanks to your votes _(and hard work from the electron userland community)_, we'll be including Ubuntu (deb) and Redhat (rpm)  x64 install files for alpha release coming before the new year :gift:!

**Comment by xsuchy** [comment]
Do you have SPEC file for RPM somewhere available? I can likely submit few enhancements.

**Comment by techninja** [comment]
@xsuchy I'm using a tool to build using SPEC file-like definitions from the package.json `releaseInfo` section. I don't have a redhat install to test against, feel free and look into the build system `build/Gruntfile.js` under `electron-installer-redhat`, line 174 😄

**Comment by xsuchy** [comment]
I am not fluent in nodejs. Can you give me please hint which arguments pass to electron-installer-redhat to genereate rpm or srpm from the git clone?
