### ISSUE TITLE
Mouse icon doesn't change to correct color

### ISSUE THREAD

**Issue by Slimmy82** [PancakeBot/PancakeCreator#40]
Not sure if this is an issue from the upgrade, but sometimes the color of the curser doesn't change to match the color selected (e.g. stays on darkest even though drawing in the lightest). That being said I have not yet issued the problem of it reverting to the default system curser.

**Comment by Slimmy82** [comment]
Scrap the last sentence. Still getting the issue of it reverting to default curser

**Comment by techninja** [comment]
Ah well. We'll see if we can't follow up with the Electron Dev Team on this one, though they're likely going to need more information about _when_ it happens and how to reproduce the issue. Document what you can and I can fill in the technical details.

**Comment by Slimmy82** [comment]
Will do thank you. I will try and screen video capture the issue.
