### ISSUE TITLE
An issue someone has with windows. 

### ISSUE THREAD

**Issue by Slimmy82** [PancakeBot/PancakeCreator#42]
I tried PancakePainter in Windows. Ok, but for Windows users I think it is very odd, that we can't specify installation directory. I don't want it on my system disk as it is SSD and so quite small. Please do something about it. Thanks

**Comment by techninja** [comment]
The streamlined installer has no such options, and installs in the users `%APPDATA%` folder regardless. We could technically switch to a more old fashioned installer, but this would both diverge us from the community supported install scheme, and require a complete rewrite of the install system and Windows build prep.

**Comment by Slimmy82** [comment]
Can you please draft up a simple sentence or short paragraph as to the advantage or way we have it the way we have it to so I have something for the complainers. I appreciate it

**Comment by techninja** [comment]
This should work:

> The PancakePainter application utilizes the worlds fastest installer for Windows, by not asking questions most users ignore anyway, and installing into the users home folder to avoid application installation security blocks. While far less adjustable, we provide a better user experience and less friction to a great majority of users.

**Comment by Slimmy82** [comment]
Thank you James,

Have a lovely weekend.

Slim Geransar
(646)706-3382
slim@storebound.commailto:slim@storebound.com

[cid:CE92FAD3-CF75-4CDD-A3D3-9B390309CBAB]

On Nov 27, 2015, at 1:35 PM, James T <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #42https://github.com/PancakeBot/PancakePainter/issues/42.
