### ISSUE TITLE
Final release doesn't print correctly 

### ISSUE THREAD

**Issue by Slimmy82** [PancakeBot/PancakeCreator#43]
Hi James,

By boss just downloaded the newest release from GitHub and tested it. He said the printing is way off. The pancake was supposed to print in the middle but the machine goes all the way to the other end and prints on the far edge. 

I got him to test it with the beta you send me (v1.0.0-Beta1S) about a week ago and it worked perfectly. So it may be that the ratio settings didn't take effect.

**Comment by techninja** [comment]
This has since been fixed with a patch applied directly to the binaries.
