### ISSUE TITLE
Error when installing on Windows

### ISSUE THREAD

**Issue by southside1** [PancakeBot/PancakeCreator#78]
whenever I try to install the software I get an error message - FIND ATTACHED ERROR - 
![aaa](https://cloud.githubusercontent.com/assets/19335895/16033128/f8b64930-3212-11e6-8c23-968105dee916.jpg)

Your urgent assistance please.

I bought this pancake a month ago and still didn't get to use it!!!

**Comment by techninja** [comment]
`PancakePainter.exe` is the name of the application, so it appears that it's not the installer that's the issue, but the main application.

A quick google search brings up [this post](https://discuss.atom.io/t/shell-notifyicongetrect-shell32-dll-error-on-vista/20159/4) that confirms my suspicions. Electron, the wrapper we use for running the application, does not support Windows Vista (as briefly explained in the download notes on the readme, "Windows 7-10").

Microsoft themselves [dropped mainline support for Windows Vista](http://windows.microsoft.com/en-us/windows/lifecycle) back in 2012, and will drop extended support in less than a year.

It's unfortunate that we can not currently support your operating system. The good news is the project is open source, and there are others working on alternative methods of GCODE creation utilizing the same code and a web browser. Hopefully soon we'll have a community of PancakeBot GCODE files available for download you can put directly on your SD card without the need for the application.
