### ISSUE TITLE
SD Card problem for the pancakebot

### ISSUE THREAD

**Issue by 3Drene** [PancakeBot/PancakeCreator#82]
Hello,

I have a problem with my SD card for my pancakebot printer.
I did put my SD card into the machine this afternoon. That went well. I could chose a design.
But, with dinner time, I put the same SD card in it and allthough the card was recognized, the PancakeBot keep saying the card was empty. Also another SD card was empty... (I couldn't choose any design.) I have the right extension on the SD card.

Can somebody help?

Hello,

I’ve got an update:
It still won’t work, but what I’ve tried:
- Two times format the SDHC card to the 32fat format. (It is a 32 GIG SDHC card)
- Put the gcode files in the root (with 5 and 6 characters)
- Put the SD card in the printer and restart it

I have a new SD card bought: 32gig, format to the 32fat format. 
The designs do not appear on the printer screen. 
The file names are all less than 8 characters long and I tried formatting it to both .pbp and .gcode file. They are in the root directory of the SD card.

Unfortunatly this didn’t worked all.
What can I do next? I really want the printer works for me.

Thanks!

Best regards, René

**Comment by techninja** [comment]
Unfortunately hardware issues are out of scope for this issue queue, please contact StoreBound directly for any hardware issues you might have.
