### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by mjackson3** [PancakeBot/PancakeCreator#95]
I am trying to open Pancake Painter on my MacBook. I downloaded the software, but I am getting the attached error message. Please help!

<img width="417" alt="screen shot 2017-05-22 at 10 34 01 am" src="https://cloud.githubusercontent.com/assets/28872023/26321134/88333008-3eda-11e7-8beb-d65275554cce.png">

**Comment by pharmpk** [comment]
Did you move the app to the Application folder (Mac). I saw somewhere else that this is needed

**Comment by techninja** [comment]
Yup, just need to move the app from the over to the user or global "Applications" folder and it should work great.
