### ISSUE TITLE
Export Failure

### ISSUE THREAD

**Issue by flamelief** [PancakeBot/PancakeCreator#97]
There is an issue with this project that doesn't allow it to be exported to gcode. 
I've attempted re-installing, using both the x86 and x64 versions of the software.

[package1.zip](https://github.com/PancakeBot/PancakePainter/files/1177921/package1.zip)

I'm running Windows 7 Professional x64.
On the 32-bit software, the Pancake Painter goes unresponsive, but is able to select buttons(no actual button actions complete).
On the 64-bit software, it provides an error message to report the error with the project file.

**Comment by techninja** [comment]
Ran this file on the latest release (1.3.0+), seems to work great. Closing this issue.
